#!/bin/sh
#
# dpmserver:   Data Processing Module Server
#
# chkconfig: 345 98 02
# description:  This is a daemon listens for data processing commands and executes them \
#               with the priviledges of the user requesting the action.
#
# Source function library.
. /etc/rc.d/init.d/functions

# Prepare environment
for i in /cmcf_apps/profile.d/*.sh; do
	if [ -r "$i" ]; then
	    . $i
	fi
done
unset i

# service parameters
servicename='dpmserver'
pidfile='/var/run/dpmserver.pid'
logfile='/var/log/dpmserver.log'
appfile='$DPM_PATH/dpm/service/dpm_server.py'
umask=022

# Sanity checks.
[ -x /usr/bin/twistd ] || exit 0
[ -f $appfile ] || exit 0

start() {
    echo -n $"Starting DPM Service: "
    daemon /usr/bin/twistd -y $appfile --logfile=$logfile --pidfile=$pidfile
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$servicename
}

stop() {
    echo -n $"Stopping DPM Service: "

    killproc $servicename -TERM
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        rm -f /var/lock/subsys/$servicename
        rm -f /var/run/$pidfile
    fi
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status -p $pidfile $servicename
        RETVAL=$?
        ;;
    restart)
        stop
	sleep 3
        start
        ;;
    condrestart)
        if [ -f /var/lock/subsys/$servicename ]; then
            stop
	    sleep 3
            start
        fi
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart}"
        ;;
esac
exit $RETVAL
