#!/bin/bash
#
# dpserver:   Data Processing Server
#
# chkconfig: 345 98 02
# description:  This is a daemon listens for data processing commands and executes them \
#               with the priviledges of the user requesting the action.
#
# Source function library.
. /etc/rc.d/init.d/functions

# Prepare environment
for profile in /cmcf_apps/profile.d/*.sh; do
	if [ -r "$profile" ]; then
	    source ${profile}
	fi
done
unset i

# services parameters
servicename='dpserver'
pidfile='/var/run/dpserver.pid'
logfile='/var/log/dpserver.log'
appfile=/path/to/auto.tac
umask=022

export MPLCONFIGDIR=/tmp

# Sanity checks.
[ -f $appfile ] || exit 0

start() {
    echo -n $"Starting Data Processing Server: "
    daemon /usr/bin/twistd -y $appfile --logfile=$logfile --umask=$umask --pidfile=$pidfile
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$servicename
}

stop() {
    echo -n $"Stopping Data Processing Server: "

    killproc -p $pidfile
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
        rm -f /var/lock/subsys/$servicename
        rm -f /var/run/$pidfile
    fi
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status -p $pidfile $servicename
        RETVAL=$?
        ;;
    restart)
        stop
	sleep 3
        start
        ;;
    condrestart)
        if [ -f /var/lock/subsys/$servicename ]; then
            stop
	    sleep 3
            start
        fi
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart}"
        ;;
esac
exit $RETVAL
